name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: star_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, pdo, bcmath
          tools: composer:v2
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader

      - name: Update Dependencies
        run: composer update --no-progress --no-suggest --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Configure Laravel ENV
        run: |
          echo "APP_ENV=testing" >> .env
          echo "APP_KEY=$(php artisan key:generate --show)" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=star_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env

      - name: Run Migrations
        run: php artisan migrate

      - name: Run Seeds
        run: php artisan db:seed

      - name: Generate API Documentation
        run: php artisan scribe:generate
